### ISSUE TITLE
How to change user password through SDK?

### ISSUE THREAD

**Issue by Byambasurenn** [aws/aws-gamekit-unreal#15]
Hello
I have successfully integrated Gamekit SDK, but how can i change user information? For example: Password, email, username etc.
Also can i customize register function? I need to add more field to it.
Thanks

**Comment by schichko** [comment]
Hi Byambasurenn,

### Change User Information through the SDK:
Can you provide some more information on what you mean by "how can i change user information"? The only field that can currently be changed after a user is registered is the user's password. If you provide some more information on the reason you need this I will bring it up to the team and make it a feature request.

If you are looking to have a user change their password they can do so with the [AwsGameKitIdentity::ForgotPassword](https://github.com/aws/aws-gamekit-unreal/blob/main/AwsGameKit/Source/AwsGameKitRuntime/Private/Identity/AwsGameKitIdentity.cpp#L83) function which is surfaced in our blueprint examples. 

If you want to change other attributes such as the User Name there is no existing functionality to accomplish that, although like I mentioned I can make a feature request. However, the mean time you can create your own logic for doing that by using the tools our plugin provides. You would be able to add a new function inside our [GameKit C++ backend](https://github.com/aws/aws-gamekit/) that does an action like change a User Name in Cognito. This new function can then be exposed and taken in by the Identity wrapper on the Unreal plugin side. 

[Here is another issue](https://github.com/aws/aws-gamekit-unreal/issues/13) where I go more in-depth on the steps needed to accomplish an end to end change like this.

### Customizing Register in the SDK:
So in order to customize the register function to add more fields you will need to edit our [GameKit C++ backend](https://github.com/aws/aws-gamekit/). Our C++ backend contains models and functions described further below that are then called, through dlls, in our Unreal plugin. Here are some of the key places you will need to edit.

1. [UserRegistration Model](https://github.com/aws/aws-gamekit/blob/main/aws-gamekit-identity/include/aws/gamekit/identity/gamekit_identity_models.h#L11) : Whatever new fields you want to add can be put in this structure ensure that these fields are also present in the [Cognito Attributes Documentation](https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_UpdateUserAttributes.html). There is a way to add [custom attrbutes](https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-settings-attributes.html) as well if what you are looking for is not found in the Attributes documentation linked earlier.

2. Then you will need to modify the [backend Identity function](https://github.com/aws/aws-gamekit/blob/main/aws-gamekit-identity/source/aws/gamekit/identity/gamekit_identity.cpp#L41) to account for any of the changes you will require. In the CognitoModel::SignUpRequest() you can add any new attributes that you want according to the [Cognito documentation](https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-settings-attributes.html).

After completing the two above points you will then need to rebuild the backend development kit and make any required changes to the Unreal side like shown in the [issue linked earlier](https://github.com/aws/aws-gamekit-unreal/issues/13)

**Comment by Byambasurenn** [comment]
Thanks for the reply. I will look at the [issue](https://github.com/aws/aws-gamekit-unreal/issues/13) you mentioned.
